name = "affiliate-link-injector"
compatibility_date = "2026-04-01"
main = "affiliate.js"

[[d1_databases]]
binding = "DB"
database_name = "saas-sites-db"
database_id = "c1ed6f24-5da9-4507-9e59-f618d98efd8a"

[[routes]]
pattern = "markdownmaster.site/*"
zone_name = "markdownmaster.site"
